### ISSUE TITLE
DtmfSendchar

### ISSUE THREAD

**Issue by mcg82** [nimaltd/DtmfGenerator#4]
Dtmf_Send the code works fine but the code(Dtmf_sendchar) doesn't work.Have you tried the Dtmf_sendchar code ?

**Comment by nimaltd** [comment]
Dtmf_sendchar('A', 100)   do you send like this?

**Comment by mcg82** [comment]
I tired again.  Dtmf_sendcahar() code works fine. I made a mistake . By the way  sorry for replying so late
